INSERT INTO `students01` (`id_number`, `name`, `score`) VALUES (1, NULL, NULL);
INSERT INTO `students01` (`id_number`, `name`, `score`) VALUES (2, 'Mike', 98);
INSERT INTO `students01` (`id_number`, `name`, `score`) VALUES (3, 'Amy', 100);
INSERT INTO `students01` (`id_number`, `name`, `score`) VALUES (4, 'Eddi', 90);
INSERT INTO `students01` (`id_number`, `name`, `score`) VALUES (5, 'Jack', 80);
INSERT INTO `students01` (`id_number`, `name`, `score`) VALUES (6, 'Simon', 90);
INSERT INTO `students01` (`id_number`, `name`, `score`) VALUES (7, 'lisa', 80);
INSERT INTO `students01` (`id_number`, `name`, `score`) VALUES (8, NULL, NULL);
INSERT INTO `students01` (`id_number`, `name`, `score`) VALUES (9, NULL, NULL);
